export const FETCH_CATEGORY_TYPES_REQUEST = 'FETCH_CATEGORY_TYPES_REQUEST'
export const FETCH_CATEGORY_TYPES_SUCCESS = 'FETCH_CATEGORY_TYPES_SUCCESS'
export const FETCH_CATEGORY_TYPES_FAILURE = 'FETCH_CATEGORY_TYPES_FAILURE'